mindfulness_exercises = [
    "2 minutes of deep belly breathing: Inhale for a count of 4, hold for 4, exhale for 4.",
    "Find a quiet spot and focus on the sensation of your breath for 2 minutes.",
    "Close your eyes and listen to the sounds around you for 1 minute.",
    "Practice a body scan: Focus on each body part, starting from your toes, for 3 minutes.",
    "Take a mindful walk around your room, paying attention to each step and sensation.",
    "Sit comfortably and name 5 things you can see, 4 things you can touch, 3 things you can hear, 2 things you can smell, and 1 thing you can taste.",
    "Hold an everyday object (e.g., a pen) and explore its texture, weight, and details for 2 minutes.",
    "Pick a word (e.g., 'peace' or 'calm') and repeat it silently for 1 minute.",
    "Visualize a calm place (e.g., a beach or forest) and immerse yourself in it for 3 minutes.",
    "Eat a small piece of food (e.g., a raisin) mindfully: Notice its texture, taste, and how you chew.",
    "Gently stretch or massage your hands and fingers, focusing on the sensations.",
    "Practice a gratitude exercise: List 3 things you're grateful for in this moment.",
    "Choose an inspiring quote and reflect on its meaning for 2 minutes.",
    "Hold an ice cube and focus on the sensation as it melts in your hand for 1 minute.",
    "Sit comfortably and focus on your breath, gently guiding your thoughts back if they wander, for 5 minutes.",
    "Draw or doodle whatever comes to mind, without judgment, for 3 minutes.",
    "Listen to a calming piece of music and pay attention to the melody and rhythm for 4 minutes.",
    "Perform a simple task (e.g., a single slow press-up) with complete attention to each movement.",
    "Write down your current thoughts and feelings, acknowledging them without judgment.",
    "Imagine your thoughts as leaves floating down a stream; watch them pass by without holding onto them.",
    "Light a scented candle and focus on the aroma as you breathe deeply for 2 minutes.",
    "Practice loving-kindness meditation: Silently repeat phrases of goodwill for yourself and others.",
    "Hold an object and explore it with your non-dominant hand, noticing new sensations.",
    "Notice 5 things around you that you hadn't noticed before.",
    "Write a short paragraph describing the present moment as if you were explaining it to someone who can't see or hear.",
    "Visualize your thoughts as clouds passing through the sky of your mind; observe them drifting away.",
    "Sit by a window and watch the outside world for 2 minutes, observing without any specific focus.",
    "Use a finger to trace the outline of your hand on a surface, feeling the movements and sensations.",
    "Perform a gentle yoga stretch or pose and focus on the stretch and your breath for 3 minutes.",
    "Practice mindful eating: Take small bites, savor the flavors, and eat slowly, paying full attention to each bite."
]

home_exercises = [
    "10 jumping jacks",
    "20 seconds of high knees",
    "15 squats",
    "10 pushups",
    "30 seconds of marching in place",
    "20 seconds of mountain climbers",
    "12 lunges (6 per leg)",
    "20 seconds of wall sit",
    "10 tricep dips using a sturdy chair",
    "15 seconds of plank",
    "20 seconds of arm circles",
    "10 leg lifts (5 per leg)",
    "20 seconds of side leg lifts (10 per side)",
    "10 calf raises",
    "15 seconds of bicycle crunches",
    "20 seconds of seated toe touches",
    "10 seconds of chair squats",
    "15 seconds of wall pushups",
    "20 seconds of seated torso twists",
    "10 seconds of balancing on one leg (each leg)",
    "15 seconds of marching while lifting knees high",
    "20 seconds of seated leg extensions",
    "10 seconds of standing side leg lifts (each leg)",
    "15 seconds of torso twists with arms outstretched",
    "20 seconds of shadow boxing",
    "10 seconds of jumping in place",
    "15 seconds of calf stretches (each leg)"
]


motivational_statements = [
    "Every step you take brings you closer to your dreams. 💪",
    "Believe in yourself and you're halfway there. 🌟",
    "You have the power to turn your dreams into reality. ✨",
    "Embrace challenges as opportunities for growth. 🌱",
    "Success comes to those who persevere with passion. 🔥",
    "Each day is a new chance to make progress. 🌈",
    "Your hard work will pay off – keep pushing forward. 🚀",
    "Stay focused and never lose sight of your goals. 🔍",
    "You're capable of more than you imagine. 💫",
    "Difficult roads often lead to beautiful destinations. 🌺",
    "Don't stop when you're tired, stop when you're done. 💯",
    "Challenges are what make life interesting. 🌄",
    "Success is a journey, not a destination. 🗺️",
    "Believe you can and you're halfway there. 🌠",
    "The only limit is the one you set in your mind. 🧠",
    "Hard work beats talent when talent doesn't work hard. ⚙️",
    "Dream big and dare to fail. 🌌",
    "You're stronger than you think. 💪",
    "Small steps forward are still progress. 🚶",
    "The best way to predict the future is to create it. 🚀",
    "Stay positive and amazing things will happen. 😃",
    "The journey of a thousand miles begins with one step. 👣",
    "You're on the path to greatness – keep going. 🌟",
    "Every setback is a setup for a comeback. 🎯",
    "Success is the sum of small efforts repeated daily. 🔁",
    "Rise up and attack the day with enthusiasm. 🌅",
    "Your attitude determines your direction. 🧭",
    "You're making progress, even if you can't see it now. 📈",
    "Believe in your potential and never give up. 🌈",
    "You are capable of achieving remarkable things. 🌄",
    "Your determination knows no bounds. ⚓",
    "Keep pushing through the challenges – you've got this! 💥",
    "You're closer to success than you were yesterday. 🌓",
    "Make today so awesome that yesterday gets jealous. 🌞",
    "The only way to do great work is to love what you do. 💼",
    "You're writing your own story of success. 📖",
    "Hard times may come, but they won't last forever. ⏳",
    "Every effort you put in is a step forward. 🏃",
    "Your potential is endless – keep unleashing it. 🚀",
    "Your dreams are worth every ounce of effort. 💭",
    "Persistence makes the impossible possible. 🔄",
    "The road to success is under construction – keep driving. 🚧",
    "Doubt kills more dreams than failure ever will. 🚫",
    "You're becoming the best version of yourself. 🌟",
    "Success is not final, failure is not fatal: It's the courage to continue that counts. 🏆",
    "You're braver than you believe, stronger than you seem, and smarter than you think. 🦸",
    "Don't watch the clock, do what it does. Keep going. ⏰",
    "The secret to getting ahead is getting started. 🚗",
    "You're a diamond – under pressure, you shine the brightest. 💎",
    "Your actions today will shape your tomorrow. 🌅",
    "Prove yourself to yourself, not others. 🌄",
    "Keep aiming high and chasing your dreams. 🌠",
    "You're creating a future filled with success and happiness. 🌻"
]

